# Generated by Django 5.0.4 on 2024-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_moviereview_showreview_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='showreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
