# Generated by Django 5.0.4 on 2024-04-11 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_moviereview_rating_showreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 11)),
        ),
    ]
