# Generated by Django 5.0.4 on 2024-04-15 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_moviereview_date_alter_showreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 15)),
        ),
        migrations.AlterField(
            model_name='showreview',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 15)),
        ),
    ]
