# Generated by Django 5.0.4 on 2024-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_moviereview_date_alter_showreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.CharField(choices=[('T', 'To Be Watched'), ('S', 'Started'), ('H', 'Halfway'), ('D', 'Done!')], default='T', max_length=1),
        ),
    ]
