# Generated by Django 5.0.4 on 2024-04-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_movie_poster_alter_show_poster'),
        ('main_app', '0009_alter_show_poster'),
    ]

    operations = [
    ]
